apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-gce-pd
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-7cb758ea-d185-4008-ad75-0833a7a37276
  labels:
    type: gce-pd
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: jenkins-disk
    fsType: ext4
  storageClassName: standard


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: devops-tools
spec:
  storageClassName: csi-gce-pd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi